from libdev.lang import get_form, format_time


def test_form():
    assert get_form(1, ('день', 'дня', 'дней')) == 'день'
    assert get_form(0, ('день', 'дня', 'дней')) == 'дней'
    assert get_form(10, ('день', 'дня', 'дней')) == 'дней'
    assert get_form(11, ('день', 'дня', 'дней')) == 'дней'
    assert get_form(12, ('день', 'дня', 'дней')) == 'дней'
    assert get_form(15, ('день', 'дня', 'дней')) == 'дней'
    assert get_form(21, ('день', 'дня', 'дней')) == 'день'
    assert get_form(22, ('день', 'дня', 'дней')) == 'дня'
    assert get_form(25, ('день', 'дня', 'дней')) == 'дней'
    assert get_form(12, ('час', 'часа', 'часов')) == 'часов'
    assert get_form(23, ('час', 'часа', 'часов')) == 'часа'
    assert get_form(101, ('час', 'часа', 'часов')) == 'час'
    assert get_form(-1, ('минута', 'минуты', 'минут')) == 'минута'
    assert get_form(-21, ('минута', 'минуты', 'минут')) == 'минута'
    assert get_form(-22, ('минута', 'минуты', 'минут')) == 'минуты'
    assert get_form(-1012, ('минута', 'минуты', 'минут')) == 'минут'
    assert get_form(-25, ('минута', 'минуты', 'минут')) == 'минут'
    assert get_form(-12, ('минута', 'минуты', 'минут')) == 'минут'

def test_format_time():
    assert format_time(0) == '0 минут'
    assert format_time(30) == '0 минут'
    assert format_time(31) == '1 минута'
    assert format_time(59) == '1 минута'
    assert format_time(60) == '1 минута'
    assert format_time(10799) == '180 минут'
    assert format_time(10800) == '3 часа'
    assert format_time(12345) == '3 часа'
    assert format_time(259200) == '3 дня'
    assert format_time(259201) == '3 дня'
    assert format_time(1036800) == '12 дней'
    assert format_time(8726400) == '101 день'
    assert format_time(-1) == '0 минут'
    assert format_time(-85) == '-1 минута'
    assert format_time(-432000) == '-5 дней'
